jobs:
  - name: cross-product
    plan:
    - get: src
    - load_var: packages
      file: src/meta/packages-to-build.json
    - across:
      - var: package
        values: ((.:packages))
      - var: go_version
        values:
          - '1.15'
          - '1.16'
      task: build
      file: src/tasks/build.yml
      vars:
        go_version: ((.:go_version))
        package: ((.:package))

resources:
  - name: src
    type: git
    icon: github
    source:
      uri: git@github.com:uhlig-it/concourse-across-spike.git
      private_key: ((github-ssh-key))
