---
platform: linux

image_resource:
  type: docker-image
  source: { repository: alpine }

params:
  region: ((region))

run:
  path: sh
  args:
    - -c
    - |
      echo "Building sales report for region '$region'"
