---
platform: linux

image_resource:
  type: docker-image
  source: { repository: alpine }

params:
  go_version: ((go_version))
  package: ((package))

run:
  path: sh
  args:
    - -c
    - |
      echo "Building package $package with Go v$go_version"
