---
platform: linux

image_resource:
  type: docker-image
  source: { repository: alpine }

inputs:
  - name: sales-data

params:
  region: ((region))

run:
  path: sh
  args:
    - -c
    - |
      echo "Region '$region' has the following sales data available:"
      ls -l sales-data/sales-data/$region/*.csv
