jobs:
  - name: cross-product-task
    plan:
    - get: src
      trigger: true
    - load_var: packages
      file: src/meta/packages-to-build.json
    - task: build
      file: src/tasks/build.yml
      vars:
        go_version: ((.:go_version))
        package: ((.:package))
      across:
      - var: package
        values: ((.:packages))
      - var: go_version
        values:
          - '1.15'
          - '1.16'

resources:
  - name: src
    type: git
    icon: github
    source:
      uri: git@github.com:uhlig-it/concourse-across-spike.git
      private_key: ((github-ssh-key))
