jobs:
  - name: build-region
    plan:
    - get: ci
    - get: sales-data
      trigger: true
    - task: compile-sales-report
      file: ci/tasks/compile-sales-report.yml
      params:
        region: ((region))

resources:
  - name: ci
    type: git
    icon: github
    source:
      uri: git@github.com:uhlig-it/concourse-across-spike.git
      private_key: ((github-ssh-key))
      paths: [ tasks/* ]

  - name: sales-data
    type: git
    icon: github
    source:
      uri: git@github.com:uhlig-it/concourse-across-spike.git
      private_key: ((github-ssh-key))
      paths: [ sales-data/* ]
